import type { Feed, GhItem } from './types'

/**
 * Bundled fixtures so the playground is usable with no network and no token.
 * The client falls back to these on any failure.
 */

const iso = (daysAgo: number): string => new Date(Date.now() - daysAgo * 86_400_000).toISOString()

const pulls: GhItem[] = [
	{
		kind: 'pr',
		number: 412,
		title: 'feat(fold-tui): amber substrate + neon graft theming',
		state: 'open',
		draft: false,
		merged: false,
		author: 'kylemistele',
		createdAt: iso(1),
		updatedAt: iso(0),
		comments: 7,
		labels: ['enhancement', 'tui'],
		// Deliberately exercises every branch of Detail.tsx's body renderer:
		// `# ` heading, `## ` heading, `- ` bullets, `inline code`, and #123 refs.
		body: [
			'# Overview',
			'Introduces a token-driven theme layer for the TUI. Supersedes #396 and',
			'clears the palette half of #410.',
			'',
			'## What changed',
			'- One high-contrast, WCAG-floored palette (`tactical`)',
			'- Post-processing stack is derived from theme tokens, not hardcoded',
			'- Every rail panel is an aggregation over the feed — see `stats.ts`',
			'',
			'## Notes',
			'The glow is O(w*h*r^2) in JS. Radius stays at 2 and toggles with `b`.',
			'Chromatic aberration only fires during a glitch burst so text stays crisp.',
			'Builds on the compaction fix in #408.',
		].join('\n'),
		url: 'https://github.com/humanlayer/fold/pull/412',
		headRef: 'feat/tui-theme',
		baseRef: 'main',
	},
	{
		kind: 'pr',
		number: 408,
		title: 'fix(fold-core): compaction drops the final assistant turn',
		state: 'closed',
		draft: false,
		merged: true,
		author: 'dexhorthy',
		createdAt: iso(4),
		updatedAt: iso(2),
		comments: 12,
		labels: ['bug', 'core'],
		body: [
			'The summarizer was slicing `messages[0..n-1]` and then appending the tail,',
			'but `n` was computed *after* the tail had already been spliced out.',
			'',
			'Added a regression test that asserts the last assistant message survives',
			'a compaction round-trip.',
		].join('\n'),
		url: 'https://github.com/humanlayer/fold/pull/408',
		headRef: 'fix/compaction-tail',
		baseRef: 'main',
	},
	{
		kind: 'pr',
		number: 401,
		title: 'wip: subagent engine streaming transcript',
		state: 'open',
		draft: true,
		merged: false,
		author: 'allisonpope',
		createdAt: iso(9),
		updatedAt: iso(3),
		comments: 2,
		labels: ['wip'],
		body: 'Do not merge. Sketching the streaming transcript surface for subagents.',
		url: 'https://github.com/humanlayer/fold/pull/401',
		headRef: 'wip/subagent-stream',
		baseRef: 'main',
	},
	{
		kind: 'pr',
		number: 396,
		title: 'chore(deps): bump effect to 4.0.0-beta.93',
		state: 'closed',
		draft: false,
		merged: false,
		author: 'renovate',
		createdAt: iso(14),
		updatedAt: iso(11),
		comments: 1,
		labels: ['dependencies'],
		body: 'Superseded by #402. Closing without merge.',
		url: 'https://github.com/humanlayer/fold/pull/396',
		headRef: 'renovate/effect',
		baseRef: 'main',
	},
	{
		kind: 'pr',
		number: 389,
		title: 'feat(fold-codex): Codex OAuth provider over @effect/ai-openai',
		state: 'closed',
		draft: false,
		merged: true,
		author: 'kylemistele',
		createdAt: iso(21),
		updatedAt: iso(18),
		comments: 5,
		labels: ['enhancement', 'providers'],
		body: 'Adds the Codex OAuth device-flow provider and wires it into the model registry.',
		url: 'https://github.com/humanlayer/fold/pull/389',
		headRef: 'feat/codex-oauth',
		baseRef: 'main',
	},
]

const issues: GhItem[] = [
	{
		kind: 'issue',
		number: 410,
		title: 'Palette quantizes hard on terminals without truecolor',
		state: 'open',
		draft: false,
		merged: false,
		author: 'sundeep',
		createdAt: iso(2),
		updatedAt: iso(0),
		comments: 4,
		labels: ['bug', 'tui', 'help wanted'],
		body: [
			'On `TERM=xterm-256color` the laser purple collapses into the amber tones',
			'and the state glyphs stop being distinguishable.',
			'',
			'Repro: `TERM=xterm-256color bun run start`',
			'',
			'Probably needs a 256-color fallback palette per theme.',
		].join('\n'),
		url: 'https://github.com/humanlayer/fold/issues/410',
	},
	{
		kind: 'issue',
		number: 405,
		title: 'Bloom pass drops us to 12fps at 220x60',
		state: 'open',
		draft: false,
		merged: false,
		author: 'mikeyobrien',
		createdAt: iso(6),
		updatedAt: iso(1),
		comments: 9,
		labels: ['performance', 'tui'],
		body: [
			'`BloomEffect.apply` allocates a `{x, y, intensity}` object per bright cell',
			'and copies both fg and bg buffers every frame.',
			'',
			'At 220x60 with a bright theme that is ~13k allocations/frame.',
			'',
			'Suggest: reuse a flat `Float32Array` scratch and skip the copy when no',
			'cell crosses the threshold.',
		].join('\n'),
		url: 'https://github.com/humanlayer/fold/issues/405',
	},
	{
		kind: 'issue',
		number: 399,
		title: "Add a 'critical' state for failed tool calls",
		state: 'open',
		draft: false,
		merged: false,
		author: 'dexhorthy',
		createdAt: iso(10),
		updatedAt: iso(5),
		comments: 3,
		labels: ['enhancement', 'design'],
		body: 'Failed tool calls should render in the alert slot, with a target-lock bracket.',
		url: 'https://github.com/humanlayer/fold/issues/399',
	},
	{
		kind: 'issue',
		number: 372,
		title: 'Flaky: activity sparkline differs by one bucket on CI',
		state: 'open',
		draft: false,
		merged: false,
		author: 'allisonpope',
		createdAt: iso(33),
		updatedAt: iso(19),
		comments: 0,
		labels: ['ci', 'flaky'],
		// Intentionally empty — exercises Detail.tsx's "(no description provided)"
		// path, the same one a `body: null` API payload collapses into via `str()`.
		body: '',
		url: 'https://github.com/humanlayer/fold/issues/372',
	},
	{
		kind: 'issue',
		number: 380,
		title: 'Terminal title is not restored on SIGTERM',
		state: 'closed',
		draft: false,
		merged: false,
		author: 'sundeep',
		createdAt: iso(30),
		updatedAt: iso(24),
		comments: 2,
		labels: ['bug'],
		body: 'Fixed by #384 — we now register the restore handler for the full `exitSignals` set.',
		url: 'https://github.com/humanlayer/fold/issues/380',
	},
]

export const DEMO_FEED: Feed = {
	repo: 'humanlayer/fold',
	pulls,
	issues,
	rateLimit: null,
	offlineReason: 'fixtures',
	authenticated: false,
}
